/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.view;

/**
 *
 * @author remar
 */
public class ViewMain extends javax.swing.JFrame {

    /**
     * Creates new form ViewMain
     */
    public ViewMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuProduct = new javax.swing.JMenu();
        jMenuItemProductNew = new javax.swing.JMenuItem();
        jMenuItemProductSearch = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuProduct.setText("Product");

        jMenuItemProductNew.setText("New");
        jMenuProduct.add(jMenuItemProductNew);

        jMenuItemProductSearch.setText("Search");
        jMenuProduct.add(jMenuItemProductSearch);

        jMenuBar1.add(jMenuProduct);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemProductNew;
    private javax.swing.JMenuItem jMenuItemProductSearch;
    private javax.swing.JMenu jMenuProduct;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JMenuItem getjMenuItemProductNew() {
        return jMenuItemProductNew;
    }

    public javax.swing.JMenuItem getjMenuItemProductSearch() {
        return jMenuItemProductSearch;
    }
}
